### ISSUE TITLE
Error attempting to run

### ISSUE THREAD

**Issue by davout1806** [ReedOei/History-Generator#4]
When I attempt to run I get the following error.

Traceback (most recent call last):
  File "/Applications/MAMP/Library/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Applications/MAMP/Library/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mikefuller/Documents/personal/code/History-Generator-master/history_generator/__main__.py", line 9, in <module>
    from simulation import Main
  File "history_generator/simulation.py", line 16, in <module>
    import culture.religion as religion
  File "history_generator/culture/religion.py", line 9, in <module>
    from god import God, DOMAINS
  File "history_generator/culture/god.py", line 3, in <module>
    import utility
ImportError: No module named utility

I see the files utility.py & utility.pyc located in internal folder. 
python version 2.7.13

Thanks.

**Comment by ReedOei** [comment]
Thanks for letting me know, I believe I fixed it (it should just read `import internal.utility as utility`).

Please let me know if that fixes the issue for you.

**Comment by davout1806** [comment]
Thanks for the fix. Looks like similar issue in internal/terrain/noise.py Changing line 9 in noise to import internal.utility as utility seems to fix it but not sure if there are issues doing that.

Do I need to set some path variable or anything?

Traceback (most recent call last):
  File "/Applications/MAMP/Library/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Applications/MAMP/Library/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mikefuller/Documents/personal/code/History-Generator-master/history_generator/__main__.py", line 9, in <module>
    from simulation import Main
  File "history_generator/simulation.py", line 20, in <module>
    import internal.terrain.noise as noise
  File "history_generator/internal/terrain/noise.py", line 9, in <module>
    import utility
ImportError: No module named utility

**Comment by ReedOei** [comment]
No it should be fine, no environment variables changes necessary. Not sure why it seems to work fine for me, to be honest.

**Comment by davout1806** [comment]
Could MAMP be causing a problem? Although using /usr/bin/python history_generator seems to do the same thing.

**Comment by ReedOei** [comment]
Possibly. I have no idea what MAMP is. To be clear, does the program even start up, or does it crash before world generation, after clicking start, etc.?

**Comment by davout1806** [comment]
MAMP is PHP+Mysql+Python+other stuff stack for Mac

Before fix it crashes before world generation.

**Comment by davout1806** [comment]
OK now I'm getting:

Generating terrain: [===============================================================================================================================================]
Generating world: [=================================================================================================================================================]
Generating rainfall patterns: [=====================================================================================================================================]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Applications/MAMP/Library/lib/python2.7/lib-tk/Tkinter.py", line 1542, in __call__
    return self.func(*args)
  File "/Applications/MAMP/Library/lib/python2.7/lib-tk/Tkinter.py", line 592, in callit
    func(*args)
  File "history_generator/simulation.py", line 473, in main_loop
    nat.handle_diplomacy()
  File "history_generator/civil/nation.py", line 912, in handle_diplomacy
    normal_war_chance = int(max(24, len(self.at_war) + 2 * self.get_tolerance() + 3 * self.relations[other.id]))
  File "history_generator/civil/nation.py", line 614, in get_tolerance
    val += person.get_tolerance_score()
  File "history_generator/civil/people.py", line 206, in get_tolerance_score
    return (1 - person.effectiveness) * (PRIEST_TOLERANCE_BONUS * 3)
NameError: global name 'person' is not defined

**Comment by ReedOei** [comment]
Okay, I believe I've fixed that bug as well. It should've been `self.effectiveness`.

**Comment by ReedOei** [comment]
Assuming fixed, so I'm closing this. Feel free to reopen or add more issues if you run into anything else, thanks!
