### ISSUE TITLE
World History button causes error

### ISSUE THREAD

**Issue by davout1806** [ReedOei/History-Generator#5]
Sorry to be a pain but clicking World History generates an error in the terminal:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Applications/MAMP/Library/lib/python2.7/lib-tk/Tkinter.py", line 1542, in __call__
    return self.func(*args)
  File "history_generator/simulation.py", line 294, in open_world_history_window
    'Attack', 'Revolt'])
  File "history_generator/internal/event_analysis.py", line 70, in __init__
    self.event_log = Analyser().search('name', '|'.join(self.event_types))
  File "history_generator/internal/event_analysis.py", line 42, in __init__
    self.event_list = self.load_events(fname)
  File "history_generator/internal/event_analysis.py", line 56, in load_events
    with open(fname) as f:
IOError: [Errno 2] No such file or directory: 'event_log.txt'

If I create a blank event_log.txt file I then get:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Applications/MAMP/Library/lib/python2.7/lib-tk/Tkinter.py", line 1542, in __call__
    return self.func(*args)
  File "history_generator/simulation.py", line 294, in open_world_history_window
    'Attack', 'Revolt'])
  File "history_generator/internal/event_analysis.py", line 70, in __init__
    self.event_log = Analyser().search('name', '|'.join(self.event_types))
  File "history_generator/internal/event_analysis.py", line 42, in __init__
    self.event_list = self.load_events(fname)
  File "history_generator/internal/event_analysis.py", line 58, in load_events
    event_list = map(events.Event.from_str, lines)
AttributeError: class Event has no attribute 'from_str'

**Comment by ReedOei** [comment]
No worries. I'd like to fix as many bugs as possible and eventually return to this project, but I've been pretty busy with other stuff for a long time now...

At any rate, I believe I fixed this bug now. The `event_log.txt` file isn't even used anymore, as I've started migrating stuff over to a database-based approach. Unfortunately, I never finished that, but at any rate, all the event log stuff is hopefully working again.
